---
# tasks file for install-node-exporters
- name: Create a directory if it does not exist
  ansible.builtin.file:
    path: /home/ubuntu/node-exporter
    state: directory
    mode: 0755

- name: Download and Unarchive node-exporter binary
  ansible.builtin.unarchive:
    src: https://github.com/prometheus/node_exporter/releases/download/v1.3.1/node_exporter-1.3.1.linux-amd64.tar.gz
    dest: /home/ubuntu/node-exporter
    remote_src: yes

- name: node-exporter service file
  ansible.builtin.copy:
    src: node-exporter-svc.service
    dest: /etc/systemd/system/node-exporter-svc.service
    mode: 0644
    owner: root
    group: root

- name: node-exporter as service
  ansible.builtin.systemd:
    name: node-exporter-svc
    daemon_reload: yes
    enabled: yes
    state: restarted    

