---
# tasks file for install-grafana

- name: Add key
  ansible.builtin.apt_key:
    url: https://packages.grafana.com/gpg.key
    state: present


- name: Add specified repository into sources list
  ansible.builtin.apt_repository:
    repo: deb https://packages.grafana.com/oss/deb stable main
    filename: grafana.list
    state: present

- name: Install grafana
  ansible.builtin.apt:
    update_cache: true
    name: 
     - apt-transport-https
     - software-properties-common 
     - wget
     - grafana 
    state: present

- name: grafana-server as service
  ansible.builtin.systemd:
    name: grafana-server
    daemon_reload: yes
    enabled: yes
    state: restarted    