---
# tasks file for install-grafana

- name: Add key
  ansible.builtin.apt_key:
    url: https://packages.grafana.com/gpg.key
    state: present


- name: Add specified repository into sources list
  ansible.builtin.apt_repository:
    repo: deb https://packages.grafana.com/oss/deb stable main
    filename: grafana.list
    state: present

- name: Install dependencies
  ansible.builtin.apt:
    update_cache: true
    name: 
     - apt-transport-https
     - software-properties-common 
     - wget
    state: present

- name: Install grafana
  ansible.builtin.apt:
    name: 
     - grafana=9.0.2
    state: present


- name: grafana-server as service
  ansible.builtin.systemd:
    name: grafana-server
    daemon_reload: yes
    enabled: yes
    state: restarted    

- name: copy datasource config file
  ansible.builtin.copy:
    src: datasource-conf-1.yml
    dest: /etc/grafana/provisioning/datasources/datasource-conf-1.yml
    mode: 0640
    owner: root
    group: grafana

- name: copy dashboard config file
  ansible.builtin.copy:
    src: dashboard-conf-1.yml
    dest: /etc/grafana/provisioning/dashboards/dashboard-conf-1.yml
    mode: 0640
    owner: root
    group: grafana

- name: Create a directory if it does not exist
  ansible.builtin.file:
    path: /var/lib/grafana/dashboards
    state: directory
    mode: 0755

- name: copy node-exporter config file
  ansible.builtin.copy:
    src: vm-details.json
    dest: /var/lib/grafana/dashboards/vm-details.json
    mode: 0644
    owner: root
    group: grafana   

- name: grafana-server as service
  ansible.builtin.systemd:
    name: grafana-server
    state: restarted  



