---
- hosts: "{{ curr_host }}"
  become: yes
  gather_facts: yes
  roles:
    - role: heartbeat
      tags: s1
    - role: recover
    - role: clean-up        
      tags: s1
    - role: heartbeat
      tags: s1
# post_tasks:    
