---
# tasks file for recover

- name: Print var
  ansible.builtin.debug:
     var: v_service_status
- name: start process
  block:
    - name: debug
      ansible.builtin.debug: msg="inside"

    - name: Stop service uuidd
      ansible.builtin.service:
       name: uuidd
       state: stopped

    - name: Stop service uuidd
      ansible.builtin.service:
       name: uuidd
       state: stopped   

    - name: find files
      find:
       paths: "{{ item }}"
       patterns: "*.log"
      with_items: 
       - "/home/ubuntu/testdir/"
       - "/home/ubuntu/testdir2/" 
      register: result

#    - name: Print var
#      ansible.builtin.debug:
#       var: item.path
#      with_items: >
#            {{ result.results.0.files }}, {{ result.results.1.files }}
##      when: false

    - name: delete files
      file:
       path: "{{ item.path }}"
       state: absent
      with_items: >
            {{ result.results.0.files }}, {{ result.results.1.files }}


    - name: Unconditionally reboot the machine
      reboot:   
         post_reboot_delay: 60
#         test_command: /opt/kafka/bin/kafka-consumer-groups.sh --bootstrap-server localhost:9092  --list
#      when: false      

#    - name: check fail
#      fail:
#       msg: Explicitly FAILED.

    - name: Set fact
      set_fact:
        v_delete_reboot: true

    - name: Start service uuidd
      ansible.builtin.service:
       name: uuidd
       state: started

    - name: Start service uuidd
      ansible.builtin.service:
       name: uuidd
       state: started    
     
    - name: Retry a task until a certain condition is met
      shell: "sudo lsof -i -P -n | grep LISTEN" # | grep 9092"
      register: result
      until: result.stdout != ""
      retries: 5
      delay: 10   


    - name: Set fact
      set_fact:
        v_services_up: true

  when: v_service_status == 'stopped' or kp_root_space.stdout | regex_replace('[G,M,K,B]') | int  < 50       

  rescue: 
   - name: Rescue Notify
     ansible.builtin.debug: msg="Rescue Notify"
     changed_when: true
     notify:
       - write file
         
   - name: Flush handlers
     meta: flush_handlers

   - name: Rethrow
     fail:
       msg: Explicitly FAILED.
